name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - 'packages/**'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: |
          # Type-check packages using their tsconfig
          cd packages/hypely && bunx tsc -p tsconfig.json --noEmit
          cd ../@hypely-mini && bunx tsc -p tsconfig.json --noEmit

      - name: Run tests
        run: echo "No tests configured yet"

      - name: Build packages
        run: |
          cd packages/hypely && bun run build
          cd ../@hypely-mini && bun run build

      - name: Done
        run: echo "CI finished"