name: Release Stable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: release-stable
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [hypely, "@hypely/mini", create-hypely]
    permissions:
      contents: write
      id-token: write
    env:
      NPM_CONFIG_PROVENANCE: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: echo "No tests configured yet"

      - name: Build ${{ matrix.package }}
        run: bun run build --filter=${{ matrix.package }}

      - name: Publish to npm (stable)
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
            PACKAGE_DIR=$(echo "${{ matrix.package }}" | sed 's/\//-/g')
            cd packages/$PACKAGE_DIR
          npm publish --tag latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release (only once)
        if: matrix.package == 'hypely'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: hypely ${{ steps.version.outputs.version }}
          body: |
            ## Changes in this release

            See [CHANGELOG.md](./CHANGELOG.md) for details.
            
            ## Published packages
            - `hypely@${{ steps.version.outputs.version }}`
            - `create-hypely@${{ steps.version.outputs.version }}`
          draft: false
          prerelease: false
