name: Release Beta

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
  workflow_dispatch:

concurrency:
  group: release-beta
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [hypely, "@hypely-mini", create-hypely]
    permissions:
      contents: write
      id-token: write
    env:
      NPM_CONFIG_PROVENANCE: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: echo "No tests configured yet"

      - name: Build package
        run: bun run build --filter=${{ matrix.package }}

      - name: Bump version to beta
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)

          cd packages/${{ matrix.package }}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          BETA_VERSION="${CURRENT_VERSION}-beta.${TIMESTAMP}"

          bun pm version $BETA_VERSION

          cd ../..
          git tag "v${BETA_VERSION}"
          git push origin "v${BETA_VERSION}"

      - name: Publish to npm (beta)
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          cd packages/${{ matrix.package }}
          npm publish --tag beta
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
